### PR TITLE
Use gen-sdk

### PR DESCRIPTION
**Pull request by danielrbradley**
- Use the `pulumi package gen-sdk` CLI command instead of taking a dependency on pu/pkg.
- This reverts commit https://github.com/pulumi/pulumi-aws-apigateway/commit/1faf92bad9271695c3e45bcac88a31e6dc34374e where it was originally attempted but had to be taken out pending some fixes in pu/pu.
- Remove gen entry point and direct dependency on pu/pkg.

### CODE REVIEW

**Review by thomas11 — APPROVED** [review]
Nice cleanup! Keeping the p/p version the same would've made the PR a bit simpler and focused on one change.

**Review by flostadler — APPROVED** [review]
Lgtm

**Comment by danielrbradley** [comment]
> Nice cleanup! Keeping the p/p version the same would've made the PR a bit simpler and focused on one change.

I think the go mod is now only used for the tests ... I'll push an update and tidy.

**Review by iwahbe — APPROVED** [review]
LGTM

**Pull request merged**
